### ISSUE TITLE
How to convert background picture with no objection to coco datasets?

### ISSUE THREAD

**Issue by bnumaomei** [spytensor/prepare_detection_dataset#11]
When csv2coco, only pictures with objections in csv file, how to convert pictures with no objection into coco datasets ?

**Comment by wangziyan1234** [comment]
@bnumaomei i have a same question   do you solve it?

**Comment by bnumaomei** [comment]
@wangziyan1234 I have solved it. Pure background images annotations "images" should be numbered as usual, but in "annotations" no bbox.

**Comment by wangziyan1234** [comment]
@bnumaomei  thank you so much~   so this code is right, i needn't to change angthing ? (Can i run it  directly?)

**Comment by bnumaomei** [comment]
@wangziyan1234 nope, you need add neg generate code

**Comment by wangziyan1234** [comment]
@bnumaomei thank u very much~ I'm a novice in this field ，i don't quite understand the meaning of neg generate , so would you please show me the code（neg generate code） if you are convenient？ 
Thank you again

**Comment by wangziyan1234** [comment]
![6}2~1 BJ18%G4S39MX%TPLF](https://user-images.githubusercontent.com/48083793/80462747-c05b4600-8969-11ea-8c10-f00031ec96b0.png)

**Comment by wangziyan1234** [comment]
@bnumaomei Can you help me see if this format is right？
![image](https://user-images.githubusercontent.com/48083793/80463250-876fa100-896a-11ea-8615-a8336d8efb54.png)

**Comment by wangziyan1234** [comment]
@bnumaomei hello
