### ISSUE TITLE
csv参数

### ISSUE THREAD

**Issue by linchunmian** [spytensor/prepare_detection_dataset#12]
你好，请问下如果一张图片由多个目标，那就有多个bbox的坐标值，那csv的格式应该是下面(1)还是(2)呢：
(1) image_path1, x1min, y1min, x1max, y1max, cat1, x2min, y2min, x2max, y2max, cat2.....
(2) image path1, x1min, y1min, x1max, y1max, cat1
     image_path1, x2min, y2min, x2max, y2max, cat2
    .....

**Comment by shinianzhihou** [comment]
我测试的第二种是成功的

**Comment by spytensor** [comment]
一行一个目标，第二种。
