### ISSUE TITLE
使用csv2coco转出来的json存在图片重复的情况

### ISSUE THREAD

**Issue by Chenliang-Gu** [spytensor/prepare_detection_dataset#14]
`    {
      "height": 2400,
      "width": 4000,
      "id": 2505,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2506,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2507,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2508,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2509,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2510,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2511,
      "file_name": "06266.jpg"
    },
    {
      "height": 2400,
      "width": 4000,
      "id": 2512,
      "file_name": "06266.jpg"
    },`

使用csv2coco转出来的json存在图片重复的情况，即一个box就生成了一张图，应该是多个box对应一张图才对

**Comment by spytensor** [comment]
@biyuruofeng 检查一下你的csv格式是否正确，代码已经用了一年多了，没有出现过你这种情况。

**Comment by Chenliang-Gu** [comment]
我csv是这样的
name | xmin | ymin | xmax | ymax | type | set
00001.jpg | 1732 | 606 | 1943 | 767 | AdC | train
00001.jpg | 3427 | 1816 | 3565 | 1949 | AdC | train
00001.jpg | 3639 | 2120 | 3711 | 2244 | AdC | train
00002.jpg | 3234 | 1884 | 3412 | 2072 | AdC | train
00003.jpg | 739 | 908 | 945 | 1171 | AdC | train
00003.jpg | 708 | 1290 | 823 | 1391 | AdC | train
00004.jpg | 2293 | 2241 | 2467 | 2348 | AdC | train
00005.jpg | 894 | 170 | 1022 | 305 | AdC | train
00006.jpg | 842 | 1069 | 950 | 1195 | AdC | train
00007.jpg | 2933 | 1901 | 3164 | 2078 | AdC | train
00008.jpg | 1009 | 1139 | 1131 | 1212 | AdC | train
00008.jpg | 3015 | 1763 | 3091 | 1858 | AdC | train
00008.jpg | 3196 | 1004 | 3306 | 1108 | AdC | train
00008.jpg | 3880 | 452 | 3978 | 550 | AdC | train
请问这个有错误吗，我是每一张图里面有好几个目标

**Comment by spytensor** [comment]
@biyuruofeng readme中给了例子，一行是一个目标，切没有表头。
```
/mfs/dataset/face/0d4c5e4f-fc3c-4d5a-906c-105.jpg,450,154,754,341,face
/mfs/dataset/face/0ddfc5aea-fcdac-421-92dad-144.jpg,143,154,344,341,face
```
你的应该改为如下格式，比赛的数据并不是直接可以使用的，看一下说明文档。
```
00001.jpg | 1732 | 606 | 1943 | 767 | AdC 
00001.jpg | 3427 | 1816 | 3565 | 1949 | AdC 
00001.jpg | 3639 | 2120 | 3711 | 2244 | AdC 
00002.jpg | 3234 | 1884 | 3412 | 2072 | AdC 
```
