### ISSUE TITLE
一个图片中多个框的csv格式

### ISSUE THREAD

**Issue by gllspeed** [spytensor/prepare_detection_dataset#2]
你好，请问下如果一张图片中有多个目标，那csv的一行对应的是一个目标框信息还是多个目标信息, 麻烦您有时间解答下，谢谢！

**Comment by spytensor** [comment]
一行一个目标框，比如:
0001.jpg,x1,y1,x2,y2,label1
0001.jpg,x1,y1,x2,y2,label2
