### ISSUE TITLE
请问您写过COCO转txt或XML格式的程序吗

### ISSUE THREAD

**Issue by riciche** [spytensor/prepare_detection_dataset#3]
您好，我最近在做一个比赛，具体是mmdetection输出的bbox的json文件转成txt或xml格式，请问您写过这方面的程序吗，谢谢您

**Comment by spytensor** [comment]
这个比较容易实现，用python的json库读取一下json文件，然后自己解析一下，用Python 的io存成txt就可以了。

**Comment by riciche** [comment]
> 这个比较容易实现，用python的json库读取一下json文件，然后自己解析一下，用Python 的io存成txt就可以了。

好的谢谢
