### ISSUE TITLE
一幅图像中有多个目标，CSV文件格式为？

### ISSUE THREAD

**Issue by jshuzi** [spytensor/prepare_detection_dataset#7]
一幅图像中有多个目标，labels.csv 形式是/path/to/image,xmin,ymin,xmax,ymax,label, xmin2, ymin2, xmax2, ymax2, label2吗？还是需要分开两条记录，
/path/to/image,xmin,ymin,xmax,ymax,label
/path/to/image,xmin2,ymin2,xmax2,ymax2,label2

**Comment by spytensor** [comment]
每一行是一个单独目标，也就是你说的第二种
